version: '3'
networks:
  development:
  test:
volumes:
  db_data:
  gem_cache:
  shared_data:
services:
  # tor:
  #   container_name: tor
  #   image: lncm/tor:0.4.5.7@sha256:a83e0d9fd1a35adf025f2f34237ec1810e2a59765988dce1dfb222ca8ef6583c
  #   restart: on-failure
  #   volumes:
  #       - .:/var/app
  #       - shared_data:/var/shared
  #       - ${PWD}/config/torrc-dev:/etc/tor/torrc
  #   ports:
  #     - "127.0.0.1:80:80"
  #   networks:
  #       - development
    # entrypoint: ./dev-tor-entrypoint.sh
  redis:
    image: redis:4.0-alpine
    command: redis-server
    networks:
      - development
      - test
    volumes:
      - shared_data:/var/shared/redis
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: web
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - development
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    env_file: .env.development
    entrypoint: dev-entrypoint.sh
    command: ['rails', 'server', '-p', '3000', '-b', '0.0.0.0']
    environment:
      RAILS_ENV: development
    depends_on:
      - redis
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: peacemaker_test
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - test
    ports:
      - 3001:3000
    stdin_open: true
    tty: true
    env_file: .env.test
    entrypoint: test-entrypoint.sh
    command: ["rspec", "spec"]
    environment:
      RAILS_ENV: test