# This is just for using 
# docker-compose -f docker-compose.production.yml build
# Run a prod instance off of docker-compose.release.yml
version: '3'
networks:
  production:
volumes:
  production_gem_cache:
  production_shared_data:
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: dakhodl/peacemaker:v0.2.1
    volumes:
      - production_shared_data:/var/shared
      - production_gem_cache:/usr/local/bundle/gems
    networks:
      - production
    ports:
      - 3000:3000
    stdin_open: true
    restart: on-failure
    tty: true
    entrypoint: production-entrypoint.sh
    command: ['rails', 'server', '-p', '3000', '-b', '0.0.0.0']
    environment:
      RAILS_ENV: production
      REDIS_URL_SIDEKIQ: "redis://redis:6379/1"