FROM ruby:2.7.5-alpine@sha256:6f64f2efcb310a80f42605790b0121991f923e10ef4e8a1deaa3f3abcf2c9fd0

ENV APP_PATH /var/app
ENV BUNDLE_VERSION 2.2.33
ENV BUNDLE_PATH /usr/local/bundle/gems
ENV TMP_PATH /tmp/
ENV RAILS_LOG_TO_STDOUT true
ENV RAILS_PORT 3000
ENV RAILS_ENV production
ENV BUNDLE_WITHOUT development:test

# install dependencies for application
RUN apk -U add --no-cache \
build-base \
git \
libxml2-dev \
libxslt-dev \
imagemagick \
tzdata \
less \
libffi-dev \
libsodium-dev \
gcompat \
libpq-dev \
&& rm -rf /var/cache/apk/* \
&& mkdir -p $APP_PATH 


RUN gem install bundler --version "$BUNDLE_VERSION" \
&& rm -rf $GEM_HOME/cache/*

# navigate to app directory
WORKDIR $APP_PATH

COPY Gemfile $APP_PATH/Gemfile
COPY Gemfile.lock $APP_PATH/Gemfile.lock
RUN bundle install

# copy entrypoint scripts and grant execution permissions
COPY ./docker-umbrel-entrypoint.sh /usr/local/bin/umbrel-entrypoint.sh
RUN chmod +x /usr/local/bin/umbrel-entrypoint.sh

COPY  . ./

EXPOSE $RAILS_PORT

ENV RAILS_SERVE_STATIC_FILES true
RUN bundle exec rake SECRET_KEY_BASE=dummyforcompilation  assets:precompile

RUN chown -R 1000:1000 ./

RUN rm -rf config/master.key

USER 1000

ENTRYPOINT [ "bundle", "exec" ]
